### ISSUE TITLE
Question: What does this module do?

### ISSUE THREAD

**Issue by Ace2213** [Coinsence/humhub-modules-xcoin#59]
Maybe consider adding a readme/docs?

Looks very interesting though

**Comment by gdalyy** [comment]
This module is responsible for accounts, transactions and crowdfunding campaigns management.

The readme will be there ASAP. thanks

**Comment by Ace2213** [comment]
I can help with the readme/docs. I'll install it and if I can figure it out, I'll submit them for your approval

**Comment by gdalyy** [comment]
It would be great , thank you @Ace2213

**Comment by Ace2213** [comment]
I enabled globally then enabled for a space and when I clicked configure, I got this:
`Error: Class 'humhub\assets\TabbedFormAsset' not found in /humhub/protected/modules/xcoin/views/config/_moduleConfigLayout.php:2 Stack trace: #0`

On profiles I ran into the issue of not having any "coin" options to select when trying to sell a product, and that field is mandatory. I'll try installing the etherium module and seeing if it fixes it.

**Comment by Ace2213** [comment]
When trying to create crowdfunding:
`yii\base\ErrorException: Trying to get property 'id' of non-object in /humhub/protected/modules/xcoin/controllers/FundingOverviewController.php:109 Stack trace: #0`

Could I be getting these errors because I don't have a wallet/account? I saw in the code that accounts are automatically created when you join the community. Does that not apply to existing accounts?

**Comment by gdalyy** [comment]
Can you give me more details about what you did exactly ?

Otherwise I'll have a new installation and try to figure it out .

**Comment by Ace2213** [comment]
All I did was install the module and enable it.

In spaces, it never worked. The config throws an error. The menu items appear but all throw errors, probably because I was unable to configure it.

In profiles/global, all the tabs appear in the profile menu, the account menu and the top menu. I can access them too, but I can't interact with any of them because I don't have a wallet, and I see no option to create one.

In both profiles and spaces, I'm able to "sell a product", but one of the required fields when submitting that form is "currency" (I think, I can't remember the name) and I have none appearing when I click on it.

**Comment by gdalyy** [comment]
1. Can you make sure that `Class 'humhub\assets\TabbedFormAsset'` exists under `path_to_project/protected/humhub/assets/TabbedFormAsset.php`

2. To sell a product , there must be at least one space , because coins is created and attached to each space.

3. Ethereum module has nothing to do with this. 

4. > yii\base\ErrorException: Trying to get property 'id' of non-object in /humhub/protected/modules/xcoin/controllers/FundingOverviewController.php:109 Stack trace: #0

For this error maybe something went wrong when creating a space , the space asset is not created , maybe because ethereum module was enabled and you did not install and run [smart contracts](https://github.com/Coinsence/coinsence-monorepo)

5. When a user is created an account is automatically created and attached to this user.

6. Please try to re-install , enable xcoin module globally, because its enabled automatically for spaces , create a space , the try to sell product from you profile or directly from the space , try also to create a crowdfunding campaign al let me know what happens.

**Comment by Ace2213** [comment]
1. It does not exist

4. I did not install that module. I'll try that now

5. I only tried with existing users and spaces. Does it not create an account for existing users and spaces? Only for new ones?
 6. Ok

**Comment by Ace2213** [comment]
I re-installed it and enabled it globally. It was not enabled automatically for spaces. I enabled it for my user and in a space, same as before. Created a new space, also same as before. I tried all the options/pages and they all throw errors. In addition to the errors I shared above, I also got these:

> PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails in /protected/vendor/yiisoft/yii2/db/Command.php:1290 Stack trace: #0 /protected/vendor/yiisoft/yii2/db/Command.php(1290): PDOStatement->execute() #1 /protected/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('DROP TABLE `xco...') #2 /protected/vendor/yiisoft/yii2/db/Migration.php(351): yii\db\Command->execute() #3 /protected/modules/xcoin/migrations/uninstall.php(10): yii\db\Migration->dropTable('xcoin_account') #4

> Error: Call to a member function getIssuedAmount() on null in /protected/modules/xcoin/views/overview/index_space.php:33 Stack trace: #0

> Error: Undefined class constant 'ETHEREUM_STATUS_DISABLED' in /protected/modules/xcoin/views/ethereum/index.php:21 Stack trace: #0

> Error: Class 'humhub\assets\TabbedFormAsset' not found in /protected/modules/xcoin/views/config/_moduleConfigLayout.php:2 Stack trace: #0

Aside from the missing Humhub asset which is odd, I figure the main issue is that I don't have smart contracts installed and running. The installation process seems above my pay grade. I'll revisit it when I can dedicate a week or so to understanding it.
